### ISSUE TITLE
Better header differentiation

### ISSUE THREAD

**Issue by Wizz4rrd** [aaaaalexis/obsidian-cupertino#100]
First off, love the theme—been using it daily, and it’s fantastic.

One small thing that's bugging me is that header levels don’t feel super distinct, especially in long notes with lots of sections. It can get a bit tricky to quickly scan and differentiate between H1, H2, H3, etc.

Right now, I’m using a custom CSS snippet to make this clearer, but I think it could be a nice improvement for the theme itself. Maybe slightly different font sizes, weights, spacing, or some other subtle styling tweaks?

Just throwing this out as a general idea—happy to chime in later with a PR or some more specific thoughts if that helps!

**Comment by aaaaalexis** [comment]
It’s been bothering me as well, however it seems that in other apps, the only differentiator between each heading level is also just font size, nothing else, so I don’t want to divert too far from that. 

Would love to see your approach, do you mind posting a screenshot?

**Comment by tmsbn** [comment]
This is an issue that bothers me too. Even I use a custom CSS snippet here, but I really like how the Border theme adds an indicator on the side of the heading, as shown in the image. 

<img width="503" alt="Image" src="https://github.com/user-attachments/assets/5c15cbb3-cb62-4382-ab80-418d2312e7c6" />

**Comment by Wizz4rrd** [comment]
I'm still fiddling every now and then with my custom CSS snippet, as I'm constantly thinking too much colours, and next time I'm thinking too less distinction. 

For now I'm at the following, but I find the spacing a bit too much (left: edit/live preview; right: view)

![Image](https://github.com/user-attachments/assets/fe6650a7-5149-47f6-b7ce-248f79e7a374)

![Image](https://github.com/user-attachments/assets/e21fe76d-3068-410e-a4a2-f88eef0d82da)


I find @tmsbn idea of an indicator on the left of the heading very good tho! 


My css at this very moment: 

```css
.cm-header-1, .markdown-source-view.mod-cm6 .cm-line h1, .markdown-preview-view h1 {
    color: var(--text-accent);
    font-size: 2.2em;
    font-weight: bold;
    margin-top: 1.8em;
    border-bottom: 3px solid var(--text-accent);
}


.cm-header-2, .markdown-source-view.mod-cm6 .cm-line h2, .markdown-preview-view h2 {
    color: #0077b6;
    font-size: 1.6em;
    font-weight: 600;
    margin-top: 1.4em;
    margin-bottom: 0.6em;
    border-bottom: 1px solid #0077b6;
    padding-bottom: 2px;
}

.cm-header-3, .markdown-source-view.mod-cm6 .cm-line h3, .markdown-preview-view h3 {
    color: #e9c46a;
    font-size: 1.4em;
    font-weight: 600;
    margin-top: 1.2em;
    margin-bottom: 0.5em;
}

.cm-header-4, .markdown-source-view.mod-cm6 .cm-line h4, .markdown-preview-view h4 {
    color: #2a9d8f;
    font-size: 1.2em;
    font-weight: 500;
    margin-top: 1em;
    margin-bottom: 0.4em;
}

.cm-header-5, .markdown-source-view.mod-cm6 .cm-line h5, .markdown-preview-view h5 {
    color: #457b9d;
    font-size: 1.1em;
    font-weight: 500;
    margin-top: 0.9em;
    margin-bottom: 0.3em;
    font-style: italic;
}

.cm-header-6, .markdown-source-view.mod-cm6 .cm-line h6, .markdown-preview-view h6 {
    color: #264653;
    font-size: 1em;
    font-weight: 400;
    margin-top: 0.8em;
    margin-bottom: 0.2em;
    text-transform: uppercase;
}
```
