### ISSUE TITLE
Issues regarding the automatic hiding of elements

### ISSUE THREAD

**Issue by cxrvus** [aaaaalexis/obsidian-cupertino#114]
I have two seperate issues regarding this:

1. renaming canvases: I would prefer that the canvas title would be visible while renaming, regardless of whether or not you hover over it 
2. canvas embeds: the title of an embedded element is only shown when hovering over the element, but you need to double click the title in order to open its content, which doesn't really work, since the title is immediately hidden when you move your cursor off of it. I would prefer if there was a delay of a couple of seconds so you can properly click on the title.

## My Temporary Fix

I'm currently fixing the issue using a hacky CSS snippet I created (mostly using ChatGPT, since I don't know CSS that well)

```css
/*Always show file headers*/

.view-header {
    opacity: 1 !important;
    visibility: visible !important;
    pointer-events: auto !important;
}

.view-header-title-container {
    opacity: 1 !important;
    visibility: visible !important;
}

.view-header-title {
    opacity: 1 !important;
    visibility: visible !important;
}

/* Force canvas node labels to always be visible */

.canvas-node-label {
    opacity: 1 !important;           /* Ensure label is visible */
    z-index: 9999 !important;        /* Keep label on top */
    top: 0px !important;             /* Keep label in its default position */
    pointer-events: auto !important; /* Ensure it’s interactive if needed */
}

/* Prevent hiding the label when node is not hovered */
.canvas-node-container:not(:hover) + .canvas-node-label {
    opacity: 1 !important;          /* Force visibility */
    top: 0px !important;            /* Keep label in its default position */
    z-index: 9999 !important;       /* Ensure label is above other elements */
}

/* Optional: Adjust label size and appearance */
.canvas-node-label {
    font-size: 12px !important;      /* Adjust font size */
    padding: 4px 8px !important;     /* Add padding for better spacing */
    background: var(--background-secondary) !important; /* Match theme background */
    border-radius: 4px !important;  /* Rounded corners */
}
```
