### ISSUE TITLE
Indentation of Embedded Notes

### ISSUE THREAD

**Issue by niemtec** [aaaaalexis/obsidian-cupertino#117]
When notes are embedded using the `![[Some Note]]` syntax the headings render too close to the border of the card that is inserted.
This needs tweaks to padding of the internal content so that it doesn't clash with the edge of the card.

It would also be good to expose a feature where the title could be hidden from embedded notes if possible through Style Settings plugin etc.

<!-- Uploading "Clashing Embedded Note.png"... —>

**Comment by aaaaalexis** [comment]
Can you upload a screenshot? It looks normal on my end. Are you on the latest version of Cupertino?

**Comment by niemtec** [comment]
Ah sorry it didn't upload with my original report

![image](https://github.com/user-attachments/assets/d1d0ea72-8918-46c5-84e8-bc78119f3ea9)

**Comment by niemtec** [comment]
I've disabled all plugins and restarted. I can still see the issue. 
The note itself is a plain note. Here's another example with just text.


<!-- Uploading "CleanShot 2025-03-01 at 4 .52.25@2x.png"... —>

**Comment by niemtec** [comment]
<!-- Uploading "CleanShot 2025-03-01 at 4 .52.25@2x.png"... —>

**Comment by niemtec** [comment]
![image](https://github.com/user-attachments/assets/0bafdb8e-03dc-4dcc-b4f4-4c72f863e263)

**Comment by niemtec** [comment]
It seems to be caused by having custom CSS. Here's the whole file in case it's something stupid I've done.

```css
img[alt*="right"] {
  float: right;
  clear: right;
  margin-left: 1rem;
  margin-bottom: 2px;
  margin-top: 2px;
}

img[alt*="left"] {
  float: left;
  clear: left;
  margin-right: 1rem;
  margin-bottom: 2px;
  margin-top: 2px;
}

img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  margin-top: 16px;
  margin-bottom: 16px;
  border-radius: 16px;
}

.internal-embed[alt*="no-title"] .markdown-embed-title {
  display: none;
}

.markdown-embed {
  border-left-width: 0px;
  padding-left: 0px;
}

.callout {
  border-radius: 16px !important;
    border-width: 0px !important;
    padding: 16px !important;
}

pre[class*="language-"] {
  border-radius: 16px;
}

table {
  margin-left: auto;
  margin-right: auto;
}
```
