### ISSUE TITLE
Add option in style settings to auto-hide properties

### ISSUE THREAD

**Issue by Buddinski88** [aaaaalexis/obsidian-cupertino#62]
Good evening,

I am using the following CSS script to automatically hide the properties and only show them when needed (hover).

```css

/* Hide Properties and show on Hover */
.markdown-preview-view, .markdown-source-view { /* Both edit and preview mode */
    .metadata-container {             
        max-height: 2.7rem;             
        opacity: 0.6;             
        overflow: hidden;             
        transition: max-height 250ms ease-in-out, opacity 250ms;
        margin-bottom: 0;         
    }
    .metadata-container:hover,
    .metadata-container:focus-within {
         max-height: 1000px;
         opacity: 1;
         transition: max-height 300ms ease-in-out, opacity 300ms;         
    }
}
  
/* Disable hover effect for tables in Minimal theme */
.markdown-preview-view table td:hover,
.markdown-preview-view table th:hover {
    background-color: inherit !important; /* Keep the original background */
    color: inherit !important; /* Keep the original text color */
}

/* --------------------------------------------   */
```

Do you think you could include such an option so that it can be controlled in the style setting?

Many thanks and best regards
Bastian
